# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/create-github-app-token@v1.11.0
      id: generate-token
      with:
        app-id: ${{ secrets.AUTH_APP_ID }}
        private-key: ${{ secrets.AUTH_APP_PRIVATE_KEY }}
        owner: ${{ github.repository_owner }} 
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
